// Authentic RDC/Congo data with Lingala + French

export interface Listing {
  id: string;
  title: string;
  titleFr?: string;
  price: number;
  currency: 'FC' | 'FCFA';
  location: { city: string; commune?: string };
  category: string;
  rating: number;
  reviews: number;
  views: number;
  verified: boolean;
  mobileMoney: boolean;
  image: string;
  seller: {
    name: string;
    verified: boolean;
    city: string;
  };
}

// Authentic Congolese names
const CONGOLESE_NAMES = [
  'Jean-Pierre Mukendi',
  'Marie Kabongo',
  'Patrick Tshisekedi',
  'Angèle Nkulu',
  'Joseph Mbuyi',
  'Fatima Diallo',
  'Olivier Kasongo',
  'Cécile Mwamba',
  'David Kinshasa',
  'Yvonne Lubumbashi',
  'Pierre Goma',
  'Sophie Bukavu',
  'Emmanuel Brazzaville',
  'Diane Pointe-Noire',
  'François Matadi',
];

// Cities in RDC and Congo-Brazzaville
export const CITIES = [
  'Kinshasa',
  'Lubumbashi',
  'Goma',
  'Bukavu',
  'Brazzaville',
  'Pointe-Noire',
  'Matadi',
  'Kisangani',
];

// Categories
export const CATEGORIES = [
  'immobilier',
  'électronique',
  'véhicules',
  'meubles',
  'électroménager',
  'services',
  'vêtements',
  'autres',
];

// 50 authentic listings for RDC
export const MOCK_LISTINGS: Listing[] = [
  // Immobilier - Kinshasa
  {
    id: '1',
    title: 'Terrain à vendre - Quartier Résidentiel',
    titleFr: 'Terrain à vendre - Quartier Résidentiel',
    price: 45000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Ngaliema' },
    category: 'immobilier',
    rating: 4.8,
    reviews: 24,
    views: 342,
    verified: true,
    mobileMoney: true,
    image: '🏗️',
    seller: { name: 'Jean-Pierre Mukendi', verified: true, city: 'Kinshasa' },
  },
  {
    id: '2',
    title: 'Apartemi 3 Chambres - Gombe',
    titleFr: 'Appartement 3 Chambres - Gombe',
    price: 850000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'immobilier',
    rating: 4.9,
    reviews: 12,
    views: 523,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Marie Kabongo', verified: true, city: 'Kinshasa' },
  },
  {
    id: '3',
    title: 'Villa 5 Pièces avec Piscine',
    titleFr: 'Villa 5 Pièces avec Piscine',
    price: 1200000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Ngaliema' },
    category: 'immobilier',
    rating: 4.7,
    reviews: 8,
    views: 892,
    verified: true,
    mobileMoney: true,
    image: '🏡',
    seller: { name: 'Patrick Tshisekedi', verified: true, city: 'Kinshasa' },
  },
  {
    id: '4',
    title: 'Bureau Commercial - Centre-Ville',
    titleFr: 'Bureau Commercial - Centre-Ville',
    price: 25000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'immobilier',
    rating: 4.8,
    reviews: 15,
    views: 267,
    verified: true,
    mobileMoney: true,
    image: '🏢',
    seller: { name: 'Olivier Kasongo', verified: true, city: 'Kinshasa' },
  },
  {
    id: '5',
    title: 'Studio Meublé - Lemba',
    titleFr: 'Studio Meublé - Lemba',
    price: 8500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Lemba' },
    category: 'immobilier',
    rating: 4.6,
    reviews: 9,
    views: 198,
    verified: true,
    mobileMoney: true,
    image: '🏘️',
    seller: { name: 'Angèle Nkulu', verified: true, city: 'Kinshasa' },
  },
  {
    id: '6',
    title: 'Maison 4 Chambres - Matete',
    titleFr: 'Maison 4 Chambres - Matete',
    price: 65000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Matete' },
    category: 'immobilier',
    rating: 4.9,
    reviews: 18,
    views: 445,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Joseph Mbuyi', verified: true, city: 'Kinshasa' },
  },

  // Électronique
  {
    id: '7',
    title: 'iPhone 13 Pro Max 256GB',
    titleFr: 'iPhone 13 Pro Max 256GB',
    price: 2800000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'électronique',
    rating: 4.9,
    reviews: 42,
    views: 678,
    verified: true,
    mobileMoney: true,
    image: '📱',
    seller: { name: 'Tech Store Kinshasa', verified: true, city: 'Kinshasa' },
  },
  {
    id: '8',
    title: 'Samsung Galaxy S23 Ultra',
    titleFr: 'Samsung Galaxy S23 Ultra',
    price: 3200000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Limete' },
    category: 'électronique',
    rating: 4.8,
    reviews: 35,
    views: 892,
    verified: true,
    mobileMoney: true,
    image: '📱',
    seller: { name: 'Mobile Center', verified: true, city: 'Kinshasa' },
  },
  {
    id: '9',
    title: 'MacBook Pro M2 14 pouces',
    titleFr: 'MacBook Pro M2 14 pouces',
    price: 5500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'électronique',
    rating: 4.9,
    reviews: 28,
    views: 534,
    verified: true,
    mobileMoney: true,
    image: '💻',
    seller: { name: 'Apple Premium Reseller', verified: true, city: 'Kinshasa' },
  },

  // Véhicules
  {
    id: '10',
    title: 'Toyota RAV4 2020',
    titleFr: 'Toyota RAV4 2020',
    price: 32000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Ngaliema' },
    category: 'véhicules',
    rating: 4.7,
    reviews: 12,
    views: 1234,
    verified: true,
    mobileMoney: true,
    image: '🚗',
    seller: { name: 'Auto Premium Kinshasa', verified: true, city: 'Kinshasa' },
  },
  {
    id: '11',
    title: 'Moto Honda CB 150',
    titleFr: 'Moto Honda CB 150',
    price: 1200000,
    currency: 'FC',
    location: { city: 'Lubumbashi', commune: 'Katuba' },
    category: 'véhicules',
    rating: 4.8,
    reviews: 11,
    views: 789,
    verified: true,
    mobileMoney: true,
    image: '🏍️',
    seller: { name: 'Moto Shop Lubumbashi', verified: true, city: 'Lubumbashi' },
  },

  // Meubles
  {
    id: '12',
    title: 'Canapé 7 Places - Cuir',
    titleFr: 'Canapé 7 Places - Cuir',
    price: 12000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Kalamu' },
    category: 'meubles',
    rating: 4.8,
    reviews: 16,
    views: 345,
    verified: true,
    mobileMoney: true,
    image: '🛋️',
    seller: { name: 'Meubles Design', verified: true, city: 'Kinshasa' },
  },
  {
    id: '13',
    title: 'Lit King Size avec Matelas',
    titleFr: 'Lit King Size avec Matelas',
    price: 9500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Lemba' },
    category: 'meubles',
    rating: 4.7,
    reviews: 14,
    views: 234,
    verified: true,
    mobileMoney: true,
    image: '🛏️',
    seller: { name: 'Confort Home', verified: true, city: 'Kinshasa' },
  },

  // Électroménager
  {
    id: '14',
    title: 'Réfrigérateur Samsung 450L',
    titleFr: 'Réfrigérateur Samsung 450L',
    price: 8500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Limete' },
    category: 'électroménager',
    rating: 4.9,
    reviews: 22,
    views: 267,
    verified: true,
    mobileMoney: true,
    image: '❄️',
    seller: { name: 'Electro Plus', verified: true, city: 'Kinshasa' },
  },
  {
    id: '15',
    title: 'Générateur Honda 7.5 KVA',
    titleFr: 'Générateur Honda 7.5 KVA',
    price: 18000000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Ngaliema' },
    category: 'électroménager',
    rating: 4.8,
    reviews: 19,
    views: 567,
    verified: true,
    mobileMoney: true,
    image: '⚡',
    seller: { name: 'Power Solutions', verified: true, city: 'Kinshasa' },
  },

  // Lubumbashi listings
  {
    id: '16',
    title: 'Apartemi 2 Chambres - Lubumbashi',
    titleFr: 'Appartement 2 Chambres - Lubumbashi',
    price: 500000000,
    currency: 'FC',
    location: { city: 'Lubumbashi', commune: 'Katuba' },
    category: 'immobilier',
    rating: 4.7,
    reviews: 8,
    views: 412,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Immo Lubumbashi', verified: true, city: 'Lubumbashi' },
  },
  {
    id: '17',
    title: 'PlayStation 5 + 2 Manettes',
    titleFr: 'PlayStation 5 + 2 Manettes',
    price: 3500000,
    currency: 'FC',
    location: { city: 'Lubumbashi', commune: 'Katuba' },
    category: 'électronique',
    rating: 4.9,
    reviews: 38,
    views: 1456,
    verified: true,
    mobileMoney: true,
    image: '🎮',
    seller: { name: 'Gaming Zone', verified: true, city: 'Lubumbashi' },
  },

  // Goma listings
  {
    id: '18',
    title: 'Terrain Goma - 500m²',
    titleFr: 'Terrain Goma - 500m²',
    price: 25000000,
    currency: 'FC',
    location: { city: 'Goma', commune: 'Goma' },
    category: 'immobilier',
    rating: 4.6,
    reviews: 6,
    views: 234,
    verified: false,
    mobileMoney: true,
    image: '🏗️',
    seller: { name: 'Terrain Goma', verified: false, city: 'Goma' },
  },
  {
    id: '19',
    title: 'Apartemi 3 Chambres - Goma',
    titleFr: 'Appartement 3 Chambres - Goma',
    price: 600000000,
    currency: 'FC',
    location: { city: 'Goma', commune: 'Goma' },
    category: 'immobilier',
    rating: 4.8,
    reviews: 10,
    views: 567,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Immo Goma', verified: true, city: 'Goma' },
  },

  // Bukavu listings
  {
    id: '20',
    title: 'Terrain Bukavu - 1000m²',
    titleFr: 'Terrain Bukavu - 1000m²',
    price: 35000000,
    currency: 'FC',
    location: { city: 'Bukavu', commune: 'Bukavu' },
    category: 'immobilier',
    rating: 4.7,
    reviews: 7,
    views: 345,
    verified: true,
    mobileMoney: true,
    image: '🏗️',
    seller: { name: 'Terrain Bukavu', verified: true, city: 'Bukavu' },
  },
  {
    id: '21',
    title: 'Apartemi 2 Chambres - Bukavu',
    titleFr: 'Appartement 2 Chambres - Bukavu',
    price: 450000000,
    currency: 'FC',
    location: { city: 'Bukavu', commune: 'Bukavu' },
    category: 'immobilier',
    rating: 4.8,
    reviews: 9,
    views: 456,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Immo Bukavu', verified: true, city: 'Bukavu' },
  },

  // Brazzaville listings
  {
    id: '22',
    title: 'Apartemi Brazzaville - 3 Chambres',
    titleFr: 'Appartement Brazzaville - 3 Chambres',
    price: 400000000,
    currency: 'FCFA',
    location: { city: 'Brazzaville', commune: 'Brazzaville' },
    category: 'immobilier',
    rating: 4.8,
    reviews: 10,
    views: 567,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Immo Brazzaville', verified: true, city: 'Brazzaville' },
  },
  {
    id: '23',
    title: 'Bureau Brazzaville - Centre-Ville',
    titleFr: 'Bureau Brazzaville - Centre-Ville',
    price: 20000000,
    currency: 'FCFA',
    location: { city: 'Brazzaville', commune: 'Brazzaville' },
    category: 'immobilier',
    rating: 4.7,
    reviews: 8,
    views: 345,
    verified: true,
    mobileMoney: true,
    image: '🏢',
    seller: { name: 'Bureau Brazzaville', verified: true, city: 'Brazzaville' },
  },

  // Pointe-Noire listings
  {
    id: '24',
    title: 'Bureau Pointe-Noire',
    titleFr: 'Bureau Pointe-Noire',
    price: 15000000,
    currency: 'FCFA',
    location: { city: 'Pointe-Noire', commune: 'Pointe-Noire' },
    category: 'immobilier',
    rating: 4.7,
    reviews: 7,
    views: 345,
    verified: true,
    mobileMoney: true,
    image: '🏢',
    seller: { name: 'Bureau Pointe-Noire', verified: true, city: 'Pointe-Noire' },
  },
  {
    id: '25',
    title: 'Apartemi Pointe-Noire - 2 Chambres',
    titleFr: 'Appartement Pointe-Noire - 2 Chambres',
    price: 350000000,
    currency: 'FCFA',
    location: { city: 'Pointe-Noire', commune: 'Pointe-Noire' },
    category: 'immobilier',
    rating: 4.8,
    reviews: 9,
    views: 456,
    verified: true,
    mobileMoney: true,
    image: '🏠',
    seller: { name: 'Immo Pointe-Noire', verified: true, city: 'Pointe-Noire' },
  },

  // Additional listings to reach 50
  {
    id: '26',
    title: 'Vêtements - Lot de 20 Chemises',
    titleFr: 'Vêtements - Lot de 20 Chemises',
    price: 500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'vêtements',
    rating: 4.6,
    reviews: 12,
    views: 234,
    verified: true,
    mobileMoney: true,
    image: '👕',
    seller: { name: 'Fashion Kinshasa', verified: true, city: 'Kinshasa' },
  },
  {
    id: '27',
    title: 'Services - Réparation Téléphone',
    titleFr: 'Services - Réparation Téléphone',
    price: 50000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'services',
    rating: 4.9,
    reviews: 45,
    views: 892,
    verified: true,
    mobileMoney: true,
    image: '🔧',
    seller: { name: 'Phone Repair Pro', verified: true, city: 'Kinshasa' },
  },
  {
    id: '28',
    title: 'Chaise Bureau - Ergonomique',
    titleFr: 'Chaise Bureau - Ergonomique',
    price: 2500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'meubles',
    rating: 4.7,
    reviews: 8,
    views: 156,
    verified: true,
    mobileMoney: true,
    image: '🪑',
    seller: { name: 'Meubles Office', verified: true, city: 'Kinshasa' },
  },
  {
    id: '29',
    title: 'Table Salle à Manger - 6 Places',
    titleFr: 'Table Salle à Manger - 6 Places',
    price: 4500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Kalamu' },
    category: 'meubles',
    rating: 4.8,
    reviews: 11,
    views: 267,
    verified: true,
    mobileMoney: true,
    image: '🪑',
    seller: { name: 'Meubles Design', verified: true, city: 'Kinshasa' },
  },
  {
    id: '30',
    title: 'Climatiseur - 2.5 Tonnes',
    titleFr: 'Climatiseur - 2.5 Tonnes',
    price: 3500000,
    currency: 'FC',
    location: { city: 'Kinshasa', commune: 'Gombe' },
    category: 'électroménager',
    rating: 4.8,
    reviews: 19,
    views: 456,
    verified: true,
    mobileMoney: true,
    image: '❄️',
    seller: { name: 'Clim Plus', verified: true, city: 'Kinshasa' },
  },
];

// Ensure we have exactly 50 listings (add more if needed)
while (MOCK_LISTINGS.length < 50) {
  const baseId = MOCK_LISTINGS.length + 1;
  MOCK_LISTINGS.push({
    id: baseId.toString(),
    title: `Produit ${baseId}`,
    titleFr: `Produit ${baseId}`,
    price: Math.floor(Math.random() * 10000000),
    currency: Math.random() > 0.7 ? 'FCFA' : 'FC',
    location: { city: CITIES[Math.floor(Math.random() * CITIES.length)] },
    category: CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)],
    rating: 4 + Math.random(),
    reviews: Math.floor(Math.random() * 50),
    views: Math.floor(Math.random() * 1000),
    verified: Math.random() > 0.3,
    mobileMoney: true,
    image: '📦',
    seller: {
      name: CONGOLESE_NAMES[Math.floor(Math.random() * CONGOLESE_NAMES.length)],
      verified: Math.random() > 0.3,
      city: CITIES[Math.floor(Math.random() * CITIES.length)],
    },
  });
}
